# Generated by Django 2.0.1 on 2018-01-19 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LoginNameEmail', models.CharField(max_length=100)),
                ('Passwd', models.CharField(blank=True, max_length=100, null=True)),
                ('Role', models.CharField(max_length=25)),
                ('Enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Actors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('RolePlayed', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Adverts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('IndexOrder', models.IntegerField(default=0)),
                ('groupings', models.TextField(blank=True, max_length=500, null=True)),
                ('Style', models.TextField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Details', models.CharField(blank=True, max_length=500, null=True)),
                ('IndexOrder', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Details', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Details', models.TextField(blank=True, max_length=2000, null=True)),
                ('MoviePicture', models.TextField(blank=True, max_length=500, null=True)),
                ('ReleaseDate', models.DateTimeField(verbose_name='Date Released')),
                ('Duration', models.BigIntegerField(default=0)),
                ('ViewersRestriction', models.TextField(blank=True, max_length=25, null=True)),
                ('Rating', models.FloatField(default=0.0)),
                ('Producers', models.TextField(blank=True, max_length=200, null=True)),
                ('Directors', models.TextField(blank=True, max_length=200, null=True)),
                ('MoviePathLocal', models.TextField(blank=True, max_length=500, null=True)),
                ('MoviePathCloud', models.TextField(blank=True, max_length=500, null=True)),
                ('Type', models.TextField(blank=True, default='Full-Movie', max_length=25, null=True)),
                ('Language', models.TextField(blank=True, max_length=45, null=True)),
                ('Genres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviews.Genres')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='moviews.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Organisation', models.CharField(max_length=100)),
                ('MoviePathType', models.CharField(default='Local', max_length=25)),
                ('Logo', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Details', models.TextField(blank=True, max_length=2000, null=True)),
                ('InitialFreedays', models.IntegerField(default=0)),
                ('Price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('FeatureAddOns', models.TextField(blank=True, max_length=500, null=True)),
                ('PremiumAddOns', models.TextField(blank=True, max_length=500, null=True)),
                ('RenewFrequency', models.TextField(blank=True, max_length=25, null=True)),
                ('Categories', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubscriptDate', models.DateTimeField(verbose_name='Date Subscribed')),
                ('NextRenewal', models.DateTimeField(verbose_name='Next Renewal')),
                ('Status', models.TextField(blank=True, max_length=25, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviews.Account')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='moviews.Category')),
            ],
        ),
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dated', models.DateTimeField(verbose_name='Date WatchListed')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviews.Account')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviews.Movies')),
            ],
        ),
        migrations.CreateModel(
            name='WatchLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ViewDate', models.DateTimeField(verbose_name='Date Viewed')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviews.Account')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviews.Movies')),
            ],
        ),
        migrations.AddField(
            model_name='adverts',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='moviews.Category'),
        ),
        migrations.AddField(
            model_name='actors',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviews.Movies'),
        ),
        migrations.AddField(
            model_name='account',
            name='subscriptionPlan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviews.SubscriptionPlan'),
        ),
    ]
