# Generated by Django 2.0.1 on 2018-01-20 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviews', '0003_auto_20180119_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='actors',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='movies',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='watchlog',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
