# Generated by Django 2.0.1 on 2018-01-22 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviews', '0004_auto_20180120_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='Type',
            field=models.TextField(blank=True, choices=[('FM', 'FullMovie'), ('TR', 'Trailer'), ('SM', 'ShortMovie')], default='FM', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='Status',
            field=models.TextField(blank=True, choices=[('AC', 'Active'), ('IA', 'InActive')], default='IA', max_length=25, null=True),
        ),
    ]
