# Generated by Django 2.0.1 on 2018-01-23 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviews', '0006_auto_20180123_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adverts',
            name='Style',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='Directors',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='Language',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='MoviePathCloud',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='MoviePathLocal',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='MoviePicture',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='Producers',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='Type',
            field=models.CharField(blank=True, choices=[('FM', 'FullMovie'), ('TR', 'Trailer'), ('SM', 'ShortMovie')], default='FM', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='ViewersRestriction',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='FeatureAddOns',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='PremiumAddOns',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='RenewFrequency',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='Status',
            field=models.CharField(blank=True, choices=[('AC', 'Active'), ('IA', 'InActive')], default='IA', max_length=25, null=True),
        ),
    ]
