# Generated by Django 2.0.1 on 2018-01-25 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moviews', '0007_auto_20180123_1030'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieGenreMap',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('genres', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='moviews.Genres')),
            ],
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='MoviePicture',
            new_name='BigPicture',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='Language',
            new_name='LanguageCC',
        ),
        migrations.RenameField(
            model_name='setting',
            old_name='MoviePathType',
            new_name='PathType',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='Genres',
        ),
        migrations.AddField(
            model_name='adverts',
            name='Type',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='Episode',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movies',
            name='Season',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movies',
            name='SmallPicture',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='moviegenremap',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='moviews.Movies'),
        ),
    ]
