# Generated by Django 2.0.1 on 2018-02-03 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moviews', '0009_movies_mediumpicture'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubMovies',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Details', models.TextField(blank=True, max_length=2000, null=True)),
                ('ShortDetails', models.CharField(blank=True, max_length=200, null=True)),
                ('BigPicture', models.CharField(blank=True, max_length=50, null=True)),
                ('mediumPicture', models.CharField(blank=True, max_length=50, null=True)),
                ('SmallPicture', models.CharField(blank=True, max_length=50, null=True)),
                ('ReleaseDate', models.DateTimeField(verbose_name='Date Released')),
                ('Duration', models.BigIntegerField(default=0)),
                ('Season', models.IntegerField(default=0)),
                ('Episode', models.IntegerField(default=0)),
                ('ViewersRestriction', models.CharField(blank=True, max_length=25, null=True)),
                ('Rating', models.FloatField(default=0.0)),
                ('Producers', models.CharField(blank=True, max_length=50, null=True)),
                ('Directors', models.CharField(blank=True, max_length=50, null=True)),
                ('MoviePathLocal', models.CharField(blank=True, max_length=50, null=True)),
                ('MoviePathCloud', models.CharField(blank=True, max_length=50, null=True)),
                ('Type', models.CharField(blank=True, choices=[('FM', 'FullMovie'), ('TR', 'Trailer'), ('SM', 'ShortMovie')], default='FM', max_length=25, null=True)),
                ('LanguageCC', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='setting',
            old_name='Logo',
            new_name='LogoPath',
        ),
        migrations.RenameField(
            model_name='setting',
            old_name='PathType',
            new_name='MoviePathType',
        ),
        migrations.AddField(
            model_name='movies',
            name='ShortDetails',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='adverts',
            name='Type',
            field=models.CharField(blank=True, choices=[('DC', 'Documentaries'), ('GR', 'Genres'), ('RC', 'Recently-Added'), ('SP', 'Staff-Picks'), ('NW', 'Networks'), ('PP', 'Popular'), ('MN', 'Movie-Nights')], default='GR', max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='submovies',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='moviews.Movies'),
        ),
    ]
