# Generated by Django 2.0.1 on 2018-02-03 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviews', '0013_auto_20180203_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='BigPicture',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='Details',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='Directors',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='MoviePathCloud',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='MoviePathLocal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='Producers',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='ShortDetails',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='SmallPicture',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='mediumPicture',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='submovies',
            name='BigPicture',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='submovies',
            name='Details',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='submovies',
            name='Directors',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='submovies',
            name='MoviePathCloud',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='submovies',
            name='MoviePathLocal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='submovies',
            name='Producers',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='submovies',
            name='ShortDetails',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='submovies',
            name='SmallPicture',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='submovies',
            name='mediumPicture',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
